from app.schemas.schemas import *

__all__ = [
    "Token",
    "TokenData",
    "LoginRequest",
    "UsuarioCreate",
    "UsuarioResponse",
    "EspecialidadeCreate",
    "EspecialidadeResponse",
    "ConvenioCreate",
    "ConvenioUpdate",
    "ConvenioResponse",
    "PacienteCreate",
    "PacienteUpdate",
    "PacienteResponse",
    "MedicoCreate",
    "MedicoUpdate",
    "MedicoResponse",
    "HorarioDisponivelCreate",
    "HorarioDisponivelResponse",
    "BloqueioHorarioCreate",
    "BloqueioHorarioResponse",
    "ConsultaCreate",
    "ConsultaUpdate",
    "ConsultaCancelar",
    "ConsultaResponse",
    "ConsultaDetalhada",
    "AdminCreate",
    "AdminResponse",
    "EstatisticasDashboard",
    "HorarioDisponivel",
    "TipoUsuario",
    "StatusConsulta"
]
